# Generated by Django 5.1.2 on 2024-10-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fBVMC', '0002_blogpost_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('courses', models.ManyToManyField(to='fBVMC.course')),
            ],
        ),
    ]
