# Generated by Django 5.1.2 on 2024-10-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0002_car_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('actors', models.ManyToManyField(to='go.actor')),
            ],
        ),
    ]
